name: Fuse Libspectrum Linux Build [ +fake glib ]
run-name: Build Libspectrum+fake glib for Linux / ${{ github.actor }} /
on: [push]
jobs:
  build:
    name: Build Fuse Libspectrum for Linux [ +fake glib ]
    runs-on: ubuntu-latest
    steps:
      - name: (1) Prepare git
        run: |
          echo "Not needed in this build"

      - name: (2) Check out repository code
        uses: actions/checkout@v3

      - name: (3) Install dependencies
        run: |
          echo "Installing dependencies .."
          echo "No dependencies in this build"

      - name: (4) Autogen.sh
        run: |
          echo "Running autogen.sh .."
          ./autogen.sh

      - name: (5) Configure for linux (fake glib)
        run: |
          echo "Running configure (fake glib) .."
          ./configure --with-fake-glib | tee ./configure.out

      - name: (6) Verify output from configure
        run: |
          message1="Internal GLib replacement: yes"
          echo "Looking for line '$message1' .."
          lines1=(`cat "./configure.out" | grep -c "$message1"`)
          if [[ "$lines1" -ne "1" ]]; then
            echo "Error: Line $message1 not found!"
            exit 1
          fi
          echo "Line '$message1' was found."

      - name: (7) Make
        run: |
          echo "Running make .."
          make

      - name: (8) Install (+sudo)
        run: |
          echo "Running make install .."
          sudo make install

      - name: (9) Run tests
        run: |
          echo "Bulding and running tests .."
          make check

      - name: (10) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
