name: Libspectrum for Linux (1)
run-name: Build and test Libspectrum for Linux (1) [ all libs, real glib ] / ${{ github.actor }} /

on:
  # Executed upon each commit pushed
  push:
  # Called from fuse app, fuse utils repos
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: '.'
      branch:
        type: string
        required: false
      # Repo is taken from var.LIBSPECTRUM_REPO, cannot be passed as input.

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path || '.' }}
    env:
      # Support push and call triggers, set env.variables
      LIBSPECTRUM_REPO: ${{ vars.LIBSPECTRUM_REPO || '' }}
      LIBSPECTRUM_BRANCH: ${{ inputs.branch || '' }}
      LIBSPECTRUM_PATH: ${{ inputs.path || '.' }}
    steps:
      - name: (1) Prepare environment
        run: |
          echo -n "Current directory: "
          pwd
          ls -la
          
          echo "Libspectrum repo: $LIBSPECTRUM_REPO"
          echo "Libspectrum branch: $LIBSPECTRUM_BRANCH"
          echo "Libspectrum path: $LIBSPECTRUM_PATH"

      - name: (2) Check out repository code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.LIBSPECTRUM_REPO }}
          ref: ${{ env.LIBSPECTRUM_BRANCH }}
          path: ${{ env.LIBSPECTRUM_PATH }}

      - name: (3) Install dependencies
        run: |
          pwd
          ls -la
          echo "Installing dependencies .."
          sudo apt install -y libaudiofile-dev

      - name: (4) Autogen.sh
        run: |
          echo "Running autogen.sh .."
          ./autogen.sh

      - name: (5) Configure for linux (real glib)
        run: |
          echo "Running configure .."
          ./configure | tee ./configure.out

      - name: (6) Verify output from configure
        run: |
          .github/scripts/in_config.sh "libspectrum is ready to be compiled"
          .github/scripts/in_config.sh "zlib support: yes"
          .github/scripts/in_config.sh "bzip2 support: yes"
          .github/scripts/in_config.sh "libgcrypt support: yes"
          .github/scripts/in_config.sh "libaudiofile support: yes"
          .github/scripts/in_config.sh "Internal GLib replacement: no"

      - name: (7) Make
        run: |
          echo "Running make .."
          make

      - name: (8) Install
        run: |
          echo "Running make install .."
          sudo make install

      - name: (9) Run tests
        run: |
          echo "Bulding and running tests .."
          make check

      - name: (10) Upload generated files
        # Need to pack files to maintain permissions (+x mainly)
        run: |
          tar -cvzf \
          libspectrum-compiled-linux.tar.gz \
          --exclude=".git" \
          --ignore-failed-read
          .

      - uses: actions/upload-artifact@v3
        with: 
          name: libspectrum-compiled-linux
          path: |
            libspectrum-compiled-linux.tar.gz

      - name: (11) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
