name: Fuse Libspectrum Windows Build [ +fake glib ]
run-name: Build Libspectrum+fake glib for Windows / ${{ github.actor }} /
on: [push]
jobs:
  build:
    name: Build Fuse Libspectrum with Cygwin [ +fake glib ]
    runs-on: windows-latest
    steps:
      - name: (1) Prepare git (autocrlf)
        run: git config --global core.autocrlf input

      - name: (2) Check out repository code
        uses: actions/checkout@v3

      - name: (3) Install Cygwin (32 bit) with libs
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86
          packages: \
            autoconf \
            automake \
            bison \
            flex \
            gcc-core \
            gcc-g++ \
            gettext-devel \
            libtool \
            make \
            mingw64-i686-bzip2 \
            mingw64-i686-gcc-core \
            mingw64-i686-gcc-g++ \
            mingw64-i686-libgcrypt \
            mingw64-i686-libgpg-error \
            mingw64-i686-libpng \
            mingw64-i686-win-iconv \
            mingw64-i686-winpthread \
            mingw64-i686-zlib \
            pkg-config

      - name: (4) Autogen.sh
        run: bash ./autogen.sh

      - name: (5) Configure for Windows
        run: bash ./configure \
              --build=i686-pc-cygwin \
              --host=i686-w64-mingw32 \
              --prefix=/usr/local/i686-w64-mingw32 \
              --disable-static \
              --with-fake-glib

      - name: (6) Make
        run: bash make
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (7) Install
        run: bash sudo make install-strip
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (8) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
