name: Fuse Libspectrum Windows Build [ +fake glib ]
run-name: Build Libspectrum+fake glib for Windows / ${{ github.actor }} /
on: [push]
jobs:
  build:
    name: Build Fuse Libspectrum with Cygwin [ +fake glib ]
    runs-on: windows-latest
    env:
      CYGWIN_NOWINPATH: 1
    steps:
      - name: (1) Prepare git (autocrlf)
        run: git config --global core.autocrlf input

      - name: (2) Check out repository code
        uses: actions/checkout@v3

      - name: (3) Install dependencies - Cygwin (32 bit) with libs
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86
          packages: \
            autoconf \
            automake \
            bison \
            flex \
            gcc-core \
            gcc-g++ \
            gettext-devel \
            libtool \
            make \
            mingw64-i686-bzip2 \
            mingw64-i686-gcc-core \
            mingw64-i686-gcc-g++ \
            mingw64-i686-libgcrypt \
            mingw64-i686-libgpg-error \
            mingw64-i686-libpng \
            mingw64-i686-win-iconv \
            mingw64-i686-winpthread \
            mingw64-i686-zlib \
            pkg-config

      - name: (4) Autogen.sh
        run: bash ./autogen.sh

      - name: (5) Configure for Windows (fake glib)
        run: bash ./configure \
              --build=i686-pc-cygwin \
              --host=i686-w64-mingw32 \
              --prefix=/usr/local/i686-w64-mingw32 \
              --disable-static \
              --with-fake-glib

      - name: (6) Verify output from configure
        run: bash |
          message1="Internal GLib replacement: yes"
          echo "Looking for line '$message1' .."
          lines1=(`cat "./configure.out" | grep -c "$message1"`)
          if [[ "$lines1" -ne "1" ]]; then
            echo "Error: Line $message1 not found!"
            exit 1
          fi
          echo "Line '$message1' was found."

      - name: (7) Make
        run: make

      - name: (8) Install
        run: make install-strip

      - name: (9) Run tests
        run: make check

      - name: (10) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
