name: Fuse Libspectrum Windows Build [ +fake glib ]
run-name: Build Libspectrum+fake glib on Windows for user ${{ github.actor }}
on: [push]
jobs:
  build:
    name: Build Fuse Libspectrum for Windows [ +fake glib ]
    runs-on: windows-latest
    steps:
      - name: (1) Check out repository code
        uses: actions/checkout@v3

      - name: (2) Install dependencies
        run: |
          echo "Installing dependencies .."

      - name: (3) Autogen.sh
        run: |
          echo "Running autogen.sh .."
          ./autogen.sh

      - name: (4) Configure for Windows
        run: |
          echo "Running configure (fake glib) .."
          ./configure --disable-static --with-fake-glib

      - name: (5) Make
        run: |
          echo "Running make .."
          make

      - name: (6) Install
        run: |
          echo "Running make install .."
          sudo make install-strip

      - name: (7) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
