name: Libspectrum for Linux
run-name: Build and test Libspectrum for Linux / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [push, pull_request]
  
jobs:
  # 1. Default = all libs enabled, fake glib no
  default:
    name: "Libspectrum + all libs (Linux, real glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "default"

  # 2. Without zlib (real glib)
  no-zlib:
    name: "Libspectrum w/o zlib (Linux, real glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-zlib"
      use_zlib: false

  # 3. Without bzip2 (real glib)
  no-bzip2:
    name: "Libspectrum w/o bzip2 (Linux, real glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-bzip2"
      use_bzip2: false

  # 4. Without libgcrypt (real glib)
  no-libgcrypt:
    name: "Libspectrum w/o libgcrypt (Linux, real glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-libgcrypt"
      use_libgcrypt: false

  # 5. Without libaudiofile (real glib)
  no-libaudiofile:
    name: "Libspectrum w/o libaudiofile (Linux, real glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-libaudiofile"
      use_libaudiofile: false

  # 6. Without all libs (real glib)
  no-libs:
    name: "Libspectrum w/o all libs (Linux, real glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-libs"
      use_zlib: false
      use_bzip2: false
      use_libgcrypt: false
      use_libaudiofile: false

  # 7. Without zlib (fake glib)
  no-zlib:
    name: "Libspectrum w/o zlib (Linux, fake glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-zlib"
      use_zlib: false
      use_fake_glib: true

  # 8. Without bzip2 (fake glib)
  no-bzip2:
    name: "Libspectrum w/o bzip2 (Linux, fake glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-bzip2"
      use_bzip2: false
      use_fake_glib: true

  # 9. Without libgcrypt (fake glib)
  no-libgcrypt:
    name: "Libspectrum w/o libgcrypt (Linux, fake glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-libgcrypt"
      use_libgcrypt: false
      use_fake_glib: true

  # 10. Without libaudiofile (fake glib)
  no-libaudiofile:
    name: "Libspectrum w/o libaudiofile (Linux, fake glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-libaudiofile"
      use_libaudiofile: false
      use_fake_glib: true

  # 11. Without all libs (fake glib)
  no-libs:
    name: "Libspectrum w/o all libs (Linux, fake glib)"
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      key: "no-libs"
      use_zlib: false
      use_bzip2: false
      use_libgcrypt: false
      use_libaudiofile: false
      use_fake_glib: true
