name: Libspectrum for Windows (all use cases)
run-name: Build and test Libspectrum for Windows (all use cases) / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [push, pull_request]
  
jobs:
  # Default = all libs enabled, fake glib is always used
  default:
    name: "Build & Test 1"
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "default"

  # Without zlib
  no-zlib:
    name: "Build & Test 2"
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "no-zlib"
      use_zlib: false

  # Without bzip2
  no-bzip2:
    name: "Build & Test 3"
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "no-bzip2"
      use_bzip2: false

  # Without libgcrypt
  no-libgcrypt:
    name: "Build & Test 4"
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "no-libgcrypt"
      use_libgcrypt: false

  # Without libaudiofile
  no-libaudiofile:
    name: "Build & Test 5"
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "no-libaudiofile"
      use_libaudiofile: false
